### ISSUE TITLE
gradient vanishment 

### ISSUE THREAD

**Issue by phelogges** [chloeguoqing/Towards-Open-Set-Identity-Preserving-Face-Synthesis#1]
Hello!
I also tried to implement this paper, but it always occurred to gradient vanishment, can you share some experience with me?

**Comment by jmgrn61** [comment]
@phelogges  Have you successfully implemented this paper? If so, could you please share your repositories?

**Comment by phelogges** [comment]
@jmgrn61 I gived up. I'm curious about this paper because of its disentanglement ideal and the free annotation, there is other [paper](https://arxiv.org/abs/1805.09730) considering this ideal, and the author also released [codes](https://github.com/agonzgarc/cross-domain-disen), maybe this will help you.
